<?php

namespace Database\Seeders;

use App\Helpers\StorageHelper;
use App\Models\Property;
use App\Models\PropertyImage;
use App\Models\PropertyManager;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $propertyManager = $this->getPropertyManager();

        // One property per type/subtype combination - fully hardcoded
        $properties = $this->getHardcodedProperties();

        foreach ($properties as $index => $propertyData) {
            $property = Property::create(array_merge($propertyData, [
                'property_manager_id' => $propertyManager->id,
            ]));

            // Load images if folder exists
            $this->loadPropertyImages($property, $index + 1);

            $this->command->info("Created: {$property->title}");
        }

        $this->command->info("\nCreated ".count($properties)." properties \n");
    }

    /**
     * Get the property manager for seeding.
     */
    private function getPropertyManager(): PropertyManager
    {
        $user = User::where('email', 'professional@test.com')->first();

        if (! $user) {
            $this->command->error('Professional user not found. Run TestUserSeeder first.');
            exit(1);
        }

        return $user->propertyManager;
    }

    /**
     * Get hardcoded properties - one per type/subtype.
     */
    private function getHardcodedProperties(): array
    {
        return [
            // APARTMENT - STUDIO
            [
                'title' => 'Compact Studio in Amsterdam Center',
                'description' => 'Charming 32m² studio apartment located in the vibrant Kinkerstraat neighborhood, perfect for students or young professionals looking to experience Amsterdam city life. This cozy studio features a smart open-plan layout with a combined living and sleeping area that maximizes every square meter. The modern kitchenette comes fully equipped with a 2-burner stove, mini-fridge, and microwave, while the private bathroom includes a shower and toilet. The apartment is situated on the 2nd floor of a typical Amsterdam building (no elevator) and benefits from good natural light. Shared laundry facilities are available in the building basement. The location is unbeatable - you\'re within a 10-minute walk to Vondelpark, 15 minutes to Central Station, and surrounded by local cafes, supermarkets, and the famous Kinkerstraat market. Public transport connections are excellent with tram lines 7 and 17 nearby. Note: Building was constructed in 1995 with energy class C, so expect moderate utility costs. Available from mid-next month, perfect timing for the new semester or a fresh start in Amsterdam.',
                'type' => 'apartment',
                'subtype' => 'studio',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 0,
                'size' => 32,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 2,
                'has_elevator' => false,
                'year_built' => 1995,
                'energy_class' => 'C',
                'thermal_insulation_class' => 'C',
                'heating_type' => 'gas',
                'kitchen_equipped' => true,
                'kitchen_separated' => false,
                'has_cellar' => false,
                'has_laundry' => true,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => null,
                'available_date' => now()->addDays(14),
                'rent_amount' => 950,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '42',
                'street_name' => 'Kinkerstraat',
                'street_line2' => null,
                'city' => 'Amsterdam',
                'state' => null,
                'postal_code' => '1053 DZ',
                'country' => 'NL',
            ],

            // APARTMENT - LOFT
            [
                'title' => 'Industrial Loft in Rotterdam',
                'description' => 'Absolutely stunning 85m² industrial loft apartment in a beautifully converted warehouse building in Rotterdam\'s trendy Katendrecht neighborhood. This unique space celebrates its industrial heritage with soaring 4-meter-high ceilings, exposed original brick walls, and massive steel-framed windows that flood the apartment with natural light. The open-plan ground floor features a generous living area perfect for entertaining, while a stylish mezzanine level houses the bedroom area with views over the main space. The modern kitchen is equipped with high-end appliances including a dishwasher, induction cooktop, and oven, seamlessly integrated into the industrial aesthetic. The bathroom features contemporary fittings with a walk-in rain shower. Additional highlights include a private storage cellar, shared laundry facilities, one exterior parking space, and secure bike storage. The building benefits from district heating and excellent insulation (energy class A), keeping utility costs surprisingly low. Located in the heart of Katendrecht\'s transformation into Rotterdam\'s hottest neighborhood, you\'re steps away from waterfront restaurants, Fenix Food Factory, and the harbor views. The building has an elevator for easy access to the 3rd floor. Perfect for creative professionals or couples who appreciate unique living spaces with character and history.',
                'type' => 'apartment',
                'subtype' => 'loft',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 1,
                'size' => 85,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 3,
                'has_elevator' => true,
                'year_built' => 2010,
                'energy_class' => 'A',
                'thermal_insulation_class' => 'A',
                'heating_type' => 'district',
                'kitchen_equipped' => true,
                'kitchen_separated' => false,
                'has_cellar' => true,
                'has_laundry' => true,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => ['bike_storage'],
                'available_date' => now()->addDays(30),
                'rent_amount' => 1650,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '125',
                'street_name' => 'Deliplein',
                'street_line2' => null,
                'city' => 'Rotterdam',
                'state' => null,
                'postal_code' => '3013 AA',
                'country' => 'NL',
            ],

            // APARTMENT - DUPLEX
            [
                'title' => '2-Level Duplex in Utrecht',
                'description' => 'Spacious 95m² duplex apartment spread over two floors in the sought-after Padualaan area near Utrecht Science Park, ideal for couples, small families, or professionals working at the university. This well-designed duplex features a private entrance leading to the ground floor, where you\'ll find a bright living room with large windows overlooking a charming 15m² private patio garden - perfect for morning coffee or summer BBQs. The separate modern kitchen is fully equipped with all appliances including dishwasher and combi-oven, plus ample counter and storage space. A convenient guest toilet completes the ground floor. Upstairs, you\'ll discover two good-sized bedrooms (one suitable for a home office) and the main bathroom with bathtub, shower, and double sink. The apartment includes one exterior parking space and is located on the ground/first floor of a well-maintained 2005 building with energy class B rating. Gas central heating keeps the space comfortable year-round. The location offers the best of both worlds: peaceful residential living with excellent proximity to Utrecht Science Park (5-minute bike ride), Utrecht University, and the Uithof campus. Supermarkets, schools, and sports facilities are nearby, while the city center is easily reached by bike or bus. The area is popular with international professionals and academics. Available in three weeks - don\'t miss this opportunity for comfortable duplex living in one of Utrecht\'s most convenient neighborhoods.',
                'type' => 'apartment',
                'subtype' => 'duplex',
                'bedrooms' => 2,
                'bathrooms' => 1.5,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 1,
                'size' => 95,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 0,
                'has_elevator' => false,
                'year_built' => 2005,
                'energy_class' => 'B',
                'thermal_insulation_class' => 'B',
                'heating_type' => 'gas',
                'kitchen_equipped' => true,
                'kitchen_separated' => true,
                'has_cellar' => false,
                'has_laundry' => false,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => true,
                'has_rooftop' => false,
                'extras' => null,
                'available_date' => now()->addDays(21),
                'rent_amount' => 1850,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '78',
                'street_name' => 'Padualaan',
                'street_line2' => null,
                'city' => 'Utrecht',
                'state' => null,
                'postal_code' => '3584 CH',
                'country' => 'NL',
            ],

            // APARTMENT - PENTHOUSE
            [
                'title' => 'Luxury Penthouse in The Hague',
                'description' => 'Exceptional 165m² penthouse apartment on the 8th floor with breathtaking panoramic views over The Hague\'s prestigious Statenkwartier neighborhood. This exclusive residence represents the pinnacle of luxury urban living, featuring floor-to-ceiling windows throughout that bathe the space in natural light while offering stunning city vistas. The expansive open-plan living and dining area (45m²) flows seamlessly onto a magnificent 45m² private rooftop terrace - an entertainer\'s dream with enough space for lounge furniture, dining setup, and planters. The state-of-the-art kitchen boasts Miele appliances, stone countertops, wine climate cabinet, and a large cooking island. The master suite includes a walk-in closet and luxurious en-suite bathroom with double vanity, rain shower, and separate bathtub. Two additional bedrooms are generously sized, sharing a second full bathroom with premium finishes. This penthouse includes two underground parking spaces, private storage cellar, and shared laundry facilities. The 2019 building features concierge service, fitness center for residents, elevator access, and advanced security systems. Energy class A+ rating with heat pump technology and air conditioning ensures year-round comfort with minimal environmental impact. Located in the heart of Statenkwartier, you\'re surrounded by boutique shops, Michelin-starred restaurants, Frederik Hendrikplein, and the beach is just 10 minutes away. This is refined living for executives, diplomats, or anyone seeking the absolute best The Hague has to offer. Available in 45 days. Serious inquiries only - invite required for viewing.',
                'type' => 'apartment',
                'subtype' => 'penthouse',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'parking_spots_interior' => 2,
                'parking_spots_exterior' => 0,
                'size' => 165,
                'balcony_size' => 45,
                'land_size' => null,
                'floor_level' => 8,
                'has_elevator' => true,
                'year_built' => 2019,
                'energy_class' => 'A+',
                'thermal_insulation_class' => 'A',
                'heating_type' => 'heat_pump',
                'kitchen_equipped' => true,
                'kitchen_separated' => false,
                'has_cellar' => true,
                'has_laundry' => true,
                'has_fireplace' => false,
                'has_air_conditioning' => true,
                'has_garden' => false,
                'has_rooftop' => true,
                'extras' => ['concierge', 'gym'],
                'available_date' => now()->addDays(45),
                'rent_amount' => 3950,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '156',
                'street_name' => 'Van Alkemadelaan',
                'street_line2' => null,
                'city' => 'The Hague',
                'state' => null,
                'postal_code' => '2597 AT',
                'country' => 'NL',
            ],

            // HOUSE - DETACHED
            [
                'title' => 'Detached Family Home in Eindhoven',
                'description' => 'Wonderful 185m² detached family home on a 320m² plot in a peaceful, green residential area of Eindhoven, perfectly suited for families with children or professionals working at the High Tech Campus. This well-maintained house offers everything a modern family needs, with four spacious bedrooms upstairs (master bedroom with en-suite shower), a main family bathroom with bathtub, and a separate guest toilet on the ground floor. The bright living room (40m²) features a cozy fireplace and French doors opening to the sunny south-facing garden - ideal for children to play safely or for weekend barbecues. The separate dining room connects to a modern fully-equipped kitchen with all appliances including dishwasher. A dedicated home office/study room is perfect for remote work. The house includes a practical utility room with laundry connections. The double garage provides secure parking for two cars plus ample storage, with additional driveway space for guest parking. Built in 2008 with energy class A rating and heat pump heating system, this home offers excellent insulation and low energy costs. The garden is mature with established trees and lawn, plus a wooden shed for garden tools and bikes. Located in a family-friendly neighborhood with playgrounds, parks, and excellent schools (international schools within 10 minutes drive). High Tech Campus is a 15-minute bike ride, while Eindhoven Airport and city center are easily accessible. Supermarkets, sports facilities, and restaurants are all nearby. Available in two months, giving you time to plan your move to this fantastic family home.',
                'type' => 'house',
                'subtype' => 'detached',
                'bedrooms' => 4,
                'bathrooms' => 2,
                'parking_spots_interior' => 2,
                'parking_spots_exterior' => 2,
                'size' => 185,
                'balcony_size' => null,
                'land_size' => 320,
                'floor_level' => null,
                'has_elevator' => false,
                'year_built' => 2008,
                'energy_class' => 'A',
                'thermal_insulation_class' => 'A',
                'heating_type' => 'heat_pump',
                'kitchen_equipped' => true,
                'kitchen_separated' => true,
                'has_cellar' => false,
                'has_laundry' => true,
                'has_fireplace' => true,
                'has_air_conditioning' => false,
                'has_garden' => true,
                'has_rooftop' => false,
                'extras' => ['home_office'],
                'available_date' => now()->addDays(60),
                'rent_amount' => 2650,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '23',
                'street_name' => 'Boschdijk',
                'street_line2' => null,
                'city' => 'Eindhoven',
                'state' => null,
                'postal_code' => '5612 HB',
                'country' => 'NL',
            ],

            // HOUSE - SEMI-DETACHED
            [
                'title' => 'Semi-Detached House in Haarlem',
                'description' => 'Charming 125m² semi-detached house on a 150m² plot in the desirable Florapark neighborhood, just a pleasant 15-minute walk from Haarlem\'s historic city center and central station. This lovely family home combines classic Dutch architecture with modern updates, offering comfortable living spaces perfect for a couple or young family. The ground floor features an open living and dining area (35m²) with original wooden floors, large windows providing abundant natural light, and a cozy working fireplace for winter evenings. The updated separate kitchen is fully equipped with modern appliances and has direct access to the sunny southwest-facing rear garden - a private oasis with mature plants, patio area, and garden shed. Upstairs you\'ll find three well-proportioned bedrooms (master bedroom 16m², two smaller bedrooms 10m² each) and the main bathroom with shower, toilet, and sink. A separate guest toilet is conveniently located on the ground floor. The property includes a single garage with space for one car and storage, plus additional driveway parking for a second vehicle. Built in 1992, the house has energy class C rating with gas central heating. The shared laundry facilities are in a utility space. Location-wise, you couldn\'t ask for better - Haarlem\'s charming city center with its boutique shops, cafes, and cultural attractions is walkable, while the train station offers direct 15-minute connections to Amsterdam. Local supermarkets, schools, parks, and the beautiful Florapark itself are all within a few minutes. The neighborhood is quiet, green, and family-friendly. Available in 4 weeks for those seeking authentic Dutch living in one of the Netherlands\' most beautiful cities.',
                'type' => 'house',
                'subtype' => 'semi-detached',
                'bedrooms' => 3,
                'bathrooms' => 1.5,
                'parking_spots_interior' => 1,
                'parking_spots_exterior' => 1,
                'size' => 125,
                'balcony_size' => null,
                'land_size' => 150,
                'floor_level' => null,
                'has_elevator' => false,
                'year_built' => 1992,
                'energy_class' => 'C',
                'thermal_insulation_class' => 'C',
                'heating_type' => 'gas',
                'kitchen_equipped' => true,
                'kitchen_separated' => true,
                'has_cellar' => false,
                'has_laundry' => true,
                'has_fireplace' => true,
                'has_air_conditioning' => false,
                'has_garden' => true,
                'has_rooftop' => false,
                'extras' => null,
                'available_date' => now()->addDays(28),
                'rent_amount' => 1950,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '67',
                'street_name' => 'Florapark',
                'street_line2' => null,
                'city' => 'Haarlem',
                'state' => null,
                'postal_code' => '2012 HJ',
                'country' => 'NL',
            ],

            // HOUSE - VILLA
            [
                'title' => 'Luxury Villa in Wassenaar',
                'description' => 'Extraordinary 380m² architectural villa situated on an expansive 850m² landscaped plot in Wassenaar\'s most exclusive residential enclave, mere minutes from the pristine North Sea beaches. This masterpiece of contemporary luxury design offers uncompromising quality and sophistication for discerning executives, diplomats, or families seeking the ultimate in refined coastal living. The grand entrance hall with double-height ceiling sets the tone, leading to a spectacular 60m² living room with fireplace, a formal dining room seating 12, and a professional-grade kitchen featuring top-of-the-line Gaggenau appliances, stone countertops, and a large island. The ground floor also includes a home cinema room with acoustic treatments and projection system, a climate-controlled wine cellar housing 200+ bottles, a wellness area with Finnish sauna, and a guest bedroom suite. Upstairs, the luxurious master suite (45m²) boasts walk-in dressing room, spa-like bathroom with freestanding tub and rain shower, and private balcony. Three additional generous bedrooms each have en-suite bathrooms and built-in wardrobes. A fifth bedroom/study offers flexibility. The meticulously landscaped garden is a private paradise featuring a heated swimming pool (12x5m), poolhouse with shower and toilet, multiple terraces for outdoor dining and lounging, mature trees, and professional lighting. The triple garage accommodates a car collection with additional storage and workshop space, while the driveway offers parking for 6+ vehicles. Built in 2015 to the highest specifications with energy class A+ rating, heat pump systems, air conditioning, underfloor heating, advanced home automation, and comprehensive security systems. Located in Wassenaar\'s prestigious Buurtweg area, you\'re equidistant from The Hague\'s diplomatic district (15 min) and the beach villages of Scheveningen and Katwijk (10 min). International schools, golf courses, riding clubs, and fine dining are all nearby. This villa represents the pinnacle of Dutch luxury real estate. Available in 3 months. Serious inquiries only - viewings by appointment with proof of income.',
                'type' => 'house',
                'subtype' => 'villa',
                'bedrooms' => 5,
                'bathrooms' => 3,
                'parking_spots_interior' => 3,
                'parking_spots_exterior' => 3,
                'size' => 380,
                'balcony_size' => null,
                'land_size' => 850,
                'floor_level' => null,
                'has_elevator' => false,
                'year_built' => 2015,
                'energy_class' => 'A+',
                'thermal_insulation_class' => 'A',
                'heating_type' => 'heat_pump',
                'kitchen_equipped' => true,
                'kitchen_separated' => true,
                'has_cellar' => true,
                'has_laundry' => true,
                'has_fireplace' => true,
                'has_air_conditioning' => true,
                'has_garden' => true,
                'has_rooftop' => false,
                'extras' => ['pool', 'sauna', 'wine_cellar', 'home_office', 'security_system'],
                'available_date' => now()->addDays(90),
                'rent_amount' => 7500,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '12',
                'street_name' => 'Buurtweg',
                'street_line2' => null,
                'city' => 'Wassenaar',
                'state' => null,
                'postal_code' => '2242 KL',
                'country' => 'NL',
            ],

            // HOUSE - BUNGALOW
            [
                'title' => 'Single-Level Bungalow in Apeldoorn',
                'description' => 'Practical and comfortable 110m² single-level bungalow on a generous 280m² plot in a quiet, established neighborhood of Apeldoorn, ideally suited for retirees, couples, or families who prefer single-floor living without stairs. This well-maintained bungalow offers all the essentials for comfortable everyday life, with three bedrooms, a spacious L-shaped living room (30m²) featuring sliding garden doors that create a seamless indoor-outdoor connection, and a separate fully-equipped kitchen with dining area. The main bathroom includes a bathtub, toilet, and sink. All rooms are located on one convenient level, eliminating the need for stairs - a significant advantage for accessibility. The attached garage provides parking for one car plus storage space, with additional driveway parking for two more vehicles. The low-maintenance rear garden is a peaceful retreat with mature hedges providing privacy, a lawn area, patio with afternoon sun, and a garden shed for tools and bikes. Built in 1985, this bungalow has energy class C rating with gas central heating - typical for its era but functional and reliable. The location is one of the property\'s strongest assets: situated in a peaceful residential area with mostly owner-occupied homes, you\'re surrounded by greenery with walking and cycling paths to nearby forests and nature areas. Local shops, medical facilities, and bus connections are within 5 minutes, while Apeldoorn city center is a 10-minute drive or bike ride away. The neighborhood is particularly popular with retirees and families seeking a quieter lifestyle close to nature. The house is move-in ready and available in just over a month. Perfect for those seeking simplicity, practicality, and single-level comfort in a green environment.',
                'type' => 'house',
                'subtype' => 'bungalow',
                'bedrooms' => 3,
                'bathrooms' => 1,
                'parking_spots_interior' => 1,
                'parking_spots_exterior' => 2,
                'size' => 110,
                'balcony_size' => null,
                'land_size' => 280,
                'floor_level' => null,
                'has_elevator' => false,
                'year_built' => 1985,
                'energy_class' => 'C',
                'thermal_insulation_class' => 'D',
                'heating_type' => 'gas',
                'kitchen_equipped' => true,
                'kitchen_separated' => true,
                'has_cellar' => false,
                'has_laundry' => false,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => true,
                'has_rooftop' => false,
                'extras' => null,
                'available_date' => now()->addDays(35),
                'rent_amount' => 1550,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '89',
                'street_name' => 'Beekstraat',
                'street_line2' => null,
                'city' => 'Apeldoorn',
                'state' => null,
                'postal_code' => '7314 GD',
                'country' => 'NL',
            ],

            // ROOM - PRIVATE_ROOM
            [
                'title' => 'Private Room in Shared House - Groningen',
                'description' => 'Cozy furnished private room (18m²) available in a friendly shared house in Groningen\'s vibrant city center, perfect for students or young professionals looking for affordable accommodation with a social atmosphere. This spacious room comes fully furnished with a comfortable bed (140x200cm), large desk with ergonomic chair, wardrobe with hanging and shelf space, and bookshelf - everything you need to move in with just your suitcase. The room has a large window providing good natural light and overlooks the quiet inner courtyard. You\'ll be sharing this lovely house with four other housemates - currently a mix of international students and young professionals aged 22-28 who enjoy a balanced lifestyle of studying/working and socializing. Common areas include a fully-equipped shared kitchen with dishwasher, dining table for 6, cozy living room with TV and comfortable seating, two shared bathrooms (one with bathtub, one with shower), and a lovely shared garden perfect for summer BBQs. There\'s also a utility room with washing machine and dryer (shared laundry facilities). The house has good sound insulation between rooms for privacy. Bike storage is available in the secure shed. The location is absolutely ideal for student life - right on Oosterstraat in the heart of Groningen, you\'re surrounded by cafes, restaurants, supermarkets, and nightlife. The university and RUG campus are within 10-15 minutes cycling, and the central train station is easily reachable. The rent is all-inclusive: utilities (gas, water, electricity), high-speed internet, and weekly cleaning of common areas are all covered - no surprise bills! We\'re looking for a friendly, responsible housemate who respects shared living and enjoys occasional dinners or drinks together. Non-smoking house. Available in one week, viewing appointments available this weekend.',
                'type' => 'room',
                'subtype' => 'private_room',
                'bedrooms' => 1,
                'bathrooms' => 0.5,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 0,
                'size' => 18,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 1,
                'has_elevator' => false,
                'year_built' => 1975,
                'energy_class' => 'D',
                'thermal_insulation_class' => 'D',
                'heating_type' => 'gas',
                'kitchen_equipped' => true,
                'kitchen_separated' => true,
                'has_cellar' => false,
                'has_laundry' => true,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => true,
                'has_rooftop' => false,
                'extras' => null,
                'available_date' => now()->addDays(7),
                'rent_amount' => 475,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '134',
                'street_name' => 'Oosterstraat',
                'street_line2' => null,
                'city' => 'Groningen',
                'state' => null,
                'postal_code' => '9711 NT',
                'country' => 'NL',
            ],

            // ROOM - STUDENT_ROOM
            [
                'title' => 'Student Room near Leiden University',
                'description' => 'Modern 16m² student room with private en-suite bathroom in a purpose-built student residence, located just 5 minutes walking distance from Leiden University\'s historic Rapenburg campus - an unbeatable location for serious students. This well-designed room maximizes space and functionality, featuring a comfortable single bed with storage drawers underneath, a spacious study desk with task lighting and ergonomic chair, a wardrobe with hanging space and shelves, and your own private bathroom with shower, toilet, and sink - no need to share facilities or queue for showers! The building, constructed in 2018 with excellent energy class A rating and district heating, features 8 student units sharing a modern communal kitchen fully equipped with cooking facilities, dishwasher, large fridge-freezers, and a dining/social area. There\'s also a comfortable common room with sofas and TV for relaxing or group study sessions. Laundry facilities with coin-operated washers and dryers are available in the building basement, and there\'s secure bike storage for all residents. The building has elevator access (room on 2nd floor) and bike storage at ground level. The student community here is international and focused, with a good balance of study and social life - regular study groups, movie nights, and occasional dinners together. The location is phenomenal for Leiden University students - you can literally roll out of bed 10 minutes before your lecture. The historic city center with its shops, cafes, libraries, and cultural venues is a 5-minute walk. Albert Heijn supermarket is around the corner, and Leiden Central Station is 10 minutes by bike for weekend trips. The rent includes heating and water, with electricity and internet billed separately based on usage (typically €30-40/month). This is student living done right - private space when you need it, community when you want it, and the perfect location for academic success. Available in two weeks, viewings by appointment.',
                'type' => 'room',
                'subtype' => 'student_room',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 0,
                'size' => 16,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 2,
                'has_elevator' => true,
                'year_built' => 2018,
                'energy_class' => 'A',
                'thermal_insulation_class' => 'A',
                'heating_type' => 'district',
                'kitchen_equipped' => true,
                'kitchen_separated' => true,
                'has_cellar' => false,
                'has_laundry' => true,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => ['bike_storage'],
                'available_date' => now()->addDays(14),
                'rent_amount' => 525,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '45',
                'street_name' => 'Rapenburg',
                'street_line2' => null,
                'city' => 'Leiden',
                'state' => null,
                'postal_code' => '2311 GE',
                'country' => 'NL',
            ],

            // ROOM - CO-LIVING
            [
                'title' => 'Modern Co-Living Space in Amsterdam',
                'description' => 'Premium 22m² private room with en-suite bathroom in Amsterdam\'s most innovative co-living concept, designed specifically for digital nomads, remote workers, and ambitious young professionals who value community, flexibility, and hassle-free living. This contemporary space represents the future of urban housing - your private sanctuary combined with incredible shared amenities and a built-in social network. Your private room is your personal retreat, featuring a comfortable bed, spacious desk for remote work, ample storage, fast WiFi (500Mbps), individual climate control, and your own modern bathroom with rain shower. But the real magic happens in the shared spaces: a stunning professional kitchen with top appliances and dining area for 20+, a dedicated coworking space with sit-stand desks, meeting pods, and unlimited coffee, a fully-equipped gym with cardio and weights, and a spectacular rooftop terrace with city views, lounge areas, and BBQ facilities. The building also includes a cinema room, game room, laundry service, bike storage, and 24/7 reception desk. What sets this apart is the vibrant community - the building hosts weekly events including networking sessions, fitness classes, skill workshops, movie nights, and communal dinners. It\'s like having built-in friends and business connections from day one. The all-inclusive rent covers literally everything: utilities, ultra-fast WiFi, weekly room cleaning, linen service, gym access, all amenities, and the community program - zero hidden costs or complications. Located on Wibautstraat in Amsterdam Oost, you\'re perfectly positioned with metro and tram at your doorstep, Amstel Station 5 minutes away, and the city center reachable in 10 minutes. The trendy Oost neighborhood offers countless cafes, restaurants, and cultural spots. Built in 2021 with energy class A+ and heat pump technology, this is sustainable, smart living. Flexible lease terms available from 3 months to 1 year. Perfect for those who want the freedom of renting with the community of ownership. Join 40+ like-minded residents from 15+ countries. Available in 10 days - apply online with short introduction video.',
                'type' => 'room',
                'subtype' => 'co-living',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 0,
                'size' => 22,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 4,
                'has_elevator' => true,
                'year_built' => 2021,
                'energy_class' => 'A+',
                'thermal_insulation_class' => 'A',
                'heating_type' => 'heat_pump',
                'kitchen_equipped' => true,
                'kitchen_separated' => true,
                'has_cellar' => false,
                'has_laundry' => true,
                'has_fireplace' => false,
                'has_air_conditioning' => true,
                'has_garden' => false,
                'has_rooftop' => true,
                'extras' => ['gym', 'coworking'],
                'available_date' => now()->addDays(10),
                'rent_amount' => 895,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '234',
                'street_name' => 'Wibautstraat',
                'street_line2' => null,
                'city' => 'Amsterdam',
                'state' => null,
                'postal_code' => '1091 GS',
                'country' => 'NL',
            ],

            // APARTMENT - TRIPLEX
            [
                'title' => '3-Level Triplex in Maastricht',
                'description' => 'Exceptional 110m² triplex apartment elegantly spread across three floors in a beautifully restored historic building on Grote Staat, right in the heart of Maastricht\'s enchanting old town. This rare gem combines period charm with modern comfort, offering a unique living experience for those who appreciate character and history. Enter through your private street-level door into the ground floor, where you\'ll find a welcoming hallway and a bright living room (25m²) with original wooden floorboards and tall windows overlooking the bustling Grote Staat. A charming spiral staircase - a focal point of the home - winds up to the first floor, where the separate kitchen and dining area await. The kitchen retains original exposed wooden ceiling beams while incorporating modern appliances, and the dining area is perfect for entertaining. Ascend once more to the second floor, home to two well-proportioned bedrooms (14m² and 12m²) with sloped ceilings and wooden beam details that create cozy, intimate spaces. The fully renovated bathroom on this floor features a modern shower, sink, and toilet. The apartment also includes a private storage cellar and a working fireplace in the living room for atmospheric winter evenings. Built in 1890, this building has been lovingly maintained while preserving its historic character - expect thick walls, original details, and that special Dutch monument ambiance. Energy class D reflects the building\'s age, though gas central heating keeps it comfortable. Location is everything here - you\'re on one of Maastricht\'s main shopping streets, surrounded by boutiques, cafes, restaurants, and cultural attractions. The Vrijthof and Markt squares are 2 minutes walk, and the Meuse River is nearby for scenic strolls. Street parking permits available. This triplex is perfect for singles or couples who want to live in a piece of history in the Netherlands\' most beautiful southern city. Available in 6 weeks. Note: three levels means stairs - not suitable for those with mobility limitations, but absolutely worth it for the charm and location.',
                'type' => 'apartment',
                'subtype' => 'triplex',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 0,
                'size' => 110,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 0,
                'has_elevator' => false,
                'year_built' => 1890,
                'energy_class' => 'D',
                'thermal_insulation_class' => 'D',
                'heating_type' => 'gas',
                'kitchen_equipped' => true,
                'kitchen_separated' => true,
                'has_cellar' => true,
                'has_laundry' => false,
                'has_fireplace' => true,
                'has_air_conditioning' => false,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => null,
                'available_date' => now()->addDays(42),
                'rent_amount' => 1575,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '28',
                'street_name' => 'Grote Staat',
                'street_line2' => null,
                'city' => 'Maastricht',
                'state' => null,
                'postal_code' => '6211 BR',
                'country' => 'NL',
            ],

            // APARTMENT - SERVICED
            [
                'title' => 'Serviced Apartment in Rotterdam',
                'description' => 'Premium 55m² fully serviced apartment combining the comfort of home with the convenience of hotel services, located in a modern residential tower on Weena in Rotterdam\'s bustling city center - the perfect solution for business travelers, relocating professionals, or anyone needing flexible temporary housing with zero hassle. This thoughtfully designed one-bedroom apartment features a comfortable living area with sofa, dining table, and smart TV, a fully equipped kitchen with dishwasher and coffee machine, a separate bedroom with hotel-quality bed and linens, and a modern bathroom with walk-in shower. The apartment comes completely furnished and styled, ready for immediate occupancy - just bring your suitcase. What elevates this beyond a regular apartment are the comprehensive services included in your rent: weekly professional housekeeping with fresh linens and towels, 24/7 reception and concierge service to handle packages and requests, access to the building\'s fitness center with modern equipment, business center with meeting rooms and printers, and on-site laundry facilities. Your monthly rate is truly all-inclusive: utilities (gas, water, electricity), high-speed WiFi (100Mbps), building services, and all amenities are covered - you\'ll never see a surprise bill. The building also offers one underground parking space with your unit, perfect for business vehicles. Built in 2017 with energy class A rating, district heating, and air conditioning, comfort is guaranteed year-round. Located directly on Weena, you\'re in Rotterdam\'s prime business district, just 3 minutes walk from Rotterdam Central Station with direct trains to Amsterdam (40 min) and Schiphol Airport (25 min). The Erasmus University, major corporate offices, and the iconic Markthal are all nearby. This serviced apartment is ideal for corporate relocations, project assignments, extended business stays, or the transition period while house-hunting. Flexible lease terms from 1 month to 12+ months available. Professional service, premium location, zero complications. Available in one week - online booking with corporate verification.',
                'type' => 'apartment',
                'subtype' => 'serviced',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'parking_spots_interior' => 1,
                'parking_spots_exterior' => 0,
                'size' => 55,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 6,
                'has_elevator' => true,
                'year_built' => 2017,
                'energy_class' => 'A',
                'thermal_insulation_class' => 'A',
                'heating_type' => 'district',
                'kitchen_equipped' => true,
                'kitchen_separated' => false,
                'has_cellar' => false,
                'has_laundry' => true,
                'has_fireplace' => false,
                'has_air_conditioning' => true,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => ['concierge', 'gym'],
                'available_date' => now()->addDays(7),
                'rent_amount' => 2100,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '88',
                'street_name' => 'Weena',
                'street_line2' => null,
                'city' => 'Rotterdam',
                'state' => null,
                'postal_code' => '3012 CM',
                'country' => 'NL',
            ],

            // COMMERCIAL - OFFICE
            [
                'title' => 'Modern Office Space in Utrecht',
                'description' => 'Professional 85m² office space in a contemporary business complex directly opposite Utrecht Central Station - an unbeatable location for companies seeking prestige, accessibility, and employee satisfaction. This turnkey office is move-in ready, featuring an open-plan workspace with abundant natural light from floor-to-ceiling windows, comfortably accommodating 6-8 workstations with room for collaboration areas. The layout includes a separate meeting room (12m²) with glass walls and presentation screen for client meetings and video calls, a modern pantry/kitchen area with coffee machine, fridge, and sink, and a private bathroom with toilet and sink. The space has been freshly painted in neutral tones with professional carpeting, pendant lighting, and climate control (heating and cooling) for year-round comfort. Technical specifications include high-speed fiber internet connection (1Gbps available), CAT6 network cabling throughout, LED lighting with motion sensors for energy efficiency, and an integrated security system with access control. The office is located on the 2nd floor of a well-maintained business complex with elevator access, professional reception area, and excellent corporate neighbors. Three dedicated parking spaces in the secure underground garage are included, with additional visitor parking available. The building also features bike storage, shower facilities for cycling commuters, and a shared conference room available for booking. Built in 2012 with energy class B rating and district heating, operating costs are transparent and reasonable (estimated €180/month service charges). The location advantage cannot be overstated: Utrecht Central Station is literally 2 minutes walk, providing direct trains to Amsterdam (25 min), Rotterdam (35 min), and Schiphol Airport (30 min). This accessibility makes it easy to attract talent from across the Randstad. The vibrant Stationsplein area offers dozens of lunch restaurants, cafes, shops, and services. Perfect for startups scaling up, consulting firms, tech companies, or satellite offices of larger corporations. The space can be customized with your branding and furniture layout. Available in one month with flexible lease terms (minimum 2 years preferred). Schedule a viewing to see how your team could thrive in this premium Utrecht location.',
                'type' => 'commercial',
                'subtype' => 'office',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 3,
                'size' => 85,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 2,
                'has_elevator' => true,
                'year_built' => 2012,
                'energy_class' => 'B',
                'thermal_insulation_class' => 'B',
                'heating_type' => 'district',
                'kitchen_equipped' => true,
                'kitchen_separated' => true,
                'has_cellar' => false,
                'has_laundry' => false,
                'has_fireplace' => false,
                'has_air_conditioning' => true,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => ['security_system'],
                'available_date' => now()->addDays(30),
                'rent_amount' => 1850,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '450',
                'street_name' => 'Stationsplein',
                'street_line2' => null,
                'city' => 'Utrecht',
                'state' => null,
                'postal_code' => '3511 ED',
                'country' => 'NL',
            ],

            // COMMERCIAL - RETAIL
            [
                'title' => 'Street-Level Retail Shop in Amsterdam',
                'description' => 'Prime 75m² street-level retail space on Utrechtsestraat, one of Amsterdam\'s most desirable shopping streets in the prestigious De Pijp neighborhood - a golden opportunity for retailers seeking high visibility and established foot traffic. This corner-location shop offers exceptional exposure with large floor-to-ceiling display windows on two sides, allowing natural light to flood the space while providing maximum visibility for your merchandise 24/7. The open-plan sales floor (55m²) features polished concrete flooring, adjustable track lighting, and clean white walls - a blank canvas ready for your brand identity and merchandising vision. The high ceilings (3.2m) create an airy, spacious feel. A separate back room (15m²) provides essential storage space for inventory, packaging materials, and supplies, with direct rear access for deliveries to avoid disturbing customers. The staff bathroom includes toilet and sink, and there\'s a small utility area with connections for a kettle/coffee maker. The space includes a professional security shutter for the storefront and a modern alarm system. The property has a cellar storage area (8m²) included for additional inventory or seasonal items. Previously operated as a successful boutique clothing store for 8 years, this space has proven retail potential. Located on Utrechtsestraat between Ferdinand Bolstraat and the famous Albert Cuyp Market, you benefit from incredible foot traffic - this is a main artery connecting De Pijp to Amsterdam\'s historic center, bustling with locals and tourists daily. The neighborhood demographic is affluent, young, and trend-conscious - perfect for fashion, lifestyle, specialty food, design, or unique concept stores. Surrounded by complementary businesses including cafes, restaurants, and other boutiques that draw customers throughout the day and evening. Metro and tram stops nearby ensure excellent accessibility. The building dates from 1960 with energy class C - typical for Amsterdam retail. Note: no dedicated parking, but this is central Amsterdam where customers arrive by bike, foot, or public transport. The rent is for the retail space only; utilities and service charges additional (estimated €250/month). This is a rare opportunity on a proven retail street - these spaces don\'t come available often. Ideal for established brands expanding to Amsterdam or ambitious entrepreneurs with a strong retail concept. Available in two weeks. Viewing by appointment - bring your business plan.',
                'type' => 'commercial',
                'subtype' => 'retail',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 0,
                'size' => 75,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 0,
                'has_elevator' => false,
                'year_built' => 1960,
                'energy_class' => 'C',
                'thermal_insulation_class' => 'C',
                'heating_type' => 'gas',
                'kitchen_equipped' => false,
                'kitchen_separated' => false,
                'has_cellar' => true,
                'has_laundry' => false,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => null,
                'available_date' => now()->addDays(14),
                'rent_amount' => 3200,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '156',
                'street_name' => 'Utrechtsestraat',
                'street_line2' => null,
                'city' => 'Amsterdam',
                'state' => null,
                'postal_code' => '1017 VT',
                'country' => 'NL',
            ],

            // INDUSTRIAL - WAREHOUSE
            [
                'title' => 'Storage Warehouse in Tilburg',
                'description' => 'Spacious 450m² warehouse facility in Tilburg\'s established industrial zone, ideal for businesses requiring storage, distribution operations, or light manufacturing capabilities with excellent logistics access. This practical warehouse offers the essential features needed for efficient operations: 6-meter-high ceilings providing excellent vertical storage capacity (perfect for pallet racking systems), a drive-in loading dock with height-adjustable platform for efficient loading/unloading of trucks and containers, reinforced concrete floors rated for heavy loads and forklift traffic, three-phase power supply (380V) throughout the space capable of supporting machinery and equipment, and two electric roller doors (4m wide x 4.5m high) for vehicle access. The warehouse space is column-free for maximum flexibility in layout and workflow design. Natural light enters through translucent roof panels, supplemented by industrial LED high-bay lighting. Gas heating keeps the space above freezing in winter (climate control can be added if needed). A small attached office area (25m²) provides workspace for administration, planning, or customer reception, with its own entrance, bathroom, and kitchenette. The property sits on a fully fenced and gated plot with ample exterior space: 10 designated parking spots for staff and visitors, a large concrete yard area suitable for container placement or outdoor storage, and excellent truck access via a dedicated access road designed for heavy vehicles. The location in Tilburg\'s Industrieweg district offers strategic advantages: direct access to major highways (A58 and A65 within 5 minutes), 20 minutes to Breda and Eindhoven, central position in the Brabant industrial corridor, and proximity to rail freight connections. The area is zoned for industrial use, accommodating most business activities. Built in 2000, the building is structurally sound with energy class E rating (typical for industrial/warehouse facilities). The rent covers the building only; utilities (electricity, gas, water) are metered separately based on usage. This warehouse is perfect for growing logistics companies, wholesalers, e-commerce fulfillment operations, light manufacturing, or businesses needing secure storage with good distribution access. Available in 3 weeks with flexible lease terms (minimum 3 years preferred). Schedule a site visit to assess suitability for your operations.',
                'type' => 'industrial',
                'subtype' => 'warehouse',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 10,
                'size' => 450,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 0,
                'has_elevator' => false,
                'year_built' => 2000,
                'energy_class' => 'E',
                'thermal_insulation_class' => 'E',
                'heating_type' => 'gas',
                'kitchen_equipped' => false,
                'kitchen_separated' => false,
                'has_cellar' => false,
                'has_laundry' => false,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => null,
                'available_date' => now()->addDays(21),
                'rent_amount' => 2800,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '34',
                'street_name' => 'Industrieweg',
                'street_line2' => null,
                'city' => 'Tilburg',
                'state' => null,
                'postal_code' => '5045 AL',
                'country' => 'NL',
            ],

            // INDUSTRIAL - FACTORY
            [
                'title' => 'Production Facility in Zaandam',
                'description' => 'Comprehensive 650m² industrial production facility in Zaandam\'s historic industrial corridor along the Zaan River, equipped and ready for serious manufacturing, assembly, or workshop operations requiring heavy-duty infrastructure. This purpose-built factory space delivers the technical capabilities needed for production: heavy-duty three-phase power supply with 200kW capacity and dedicated transformer, overhead bridge crane system (10-ton capacity) running the full length of the production hall for material handling, industrial compressed air system with distribution points throughout the facility, specialized drainage system with oil/water separator for industrial processes compliance, 7-meter ceiling height in the main production area allowing for tall equipment and ventilation systems, and reinforced concrete floors designed for heavy machinery vibration and loads. The facility is divided into functional zones: the main production hall (500m²) with excellent natural light from north-facing sawtooth roof windows, a dedicated assembly/quality control area (80m²) with workbenches and testing stations, a materials storage area with pallet racking, and a shipping/receiving zone with two loading bays. A completely separate office building (70m²) attached to the production area houses administrative spaces, meeting room, and break room - keeping office operations distinct from production. Employee facilities include two bathrooms, changing rooms with lockers, and a lunch room with kitchen appliances. The property benefits from its own secure fenced yard (200m²) with electronic gate access, perfect for material storage, equipment parking, or container placement. Truck access is excellent via a dedicated industrial access road, and there are 15 marked parking spaces for staff and visitors. Located on Verlengde Halkade in Zaandam\'s traditional industrial zone, you\'re in the heart of the Amsterdam Metropolitan Area\'s manufacturing belt with strong logistics infrastructure: A8 motorway access within 5 minutes providing connections across the Randstad, Amsterdam city center 15 minutes, Schiphol Airport 25 minutes, and the Port of Amsterdam nearby for international shipping. The area maintains active industrial zoning permitting manufacturing, and you\'ll find supplier networks and technical services readily available. Built in 1995 and well-maintained, this facility includes a comprehensive security system with cameras and alarm. Energy class F reflects industrial usage patterns. The rent covers the building and yard; utilities (significant electricity for production equipment), water, and gas are metered separately based on consumption. This production facility is ideal for manufacturers scaling up operations, specialized engineering firms, prototype development, assembly operations, or workshop-based businesses requiring serious infrastructure. The overhead crane alone represents massive value. Available in 2 months with lease terms negotiable (minimum 5 years preferred for industrial tenants). Site visits by appointment - bring your production requirements and we\'ll discuss facility customization options.',
                'type' => 'industrial',
                'subtype' => 'factory',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 15,
                'size' => 650,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 0,
                'has_elevator' => false,
                'year_built' => 1995,
                'energy_class' => 'F',
                'thermal_insulation_class' => 'E',
                'heating_type' => 'gas',
                'kitchen_equipped' => false,
                'kitchen_separated' => false,
                'has_cellar' => false,
                'has_laundry' => false,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => ['security_system'],
                'available_date' => now()->addDays(60),
                'rent_amount' => 4500,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '67',
                'street_name' => 'Verlengde Halkade',
                'street_line2' => null,
                'city' => 'Zaandam',
                'state' => null,
                'postal_code' => '1503 MA',
                'country' => 'NL',
            ],

            // PARKING - GARAGE
            [
                'title' => 'Private Garage in The Hague',
                'description' => 'Secure private garage box (18m²) in a quiet residential area of The Hague, offering protected parking and valuable storage space - a rare commodity in the city center where street parking is both expensive and unreliable. This standalone garage box is perfect for car owners who want to protect their vehicle from weather and theft while gaining extra storage capacity. The garage measures approximately 5.5m deep x 3.3m wide with 2.2m height, easily accommodating a standard sedan, hatchback, or small SUV up to 4.8m in length. The structure features a solid concrete floor, brick walls, and a weatherproof roof keeping your vehicle dry year-round. Access is via a lockable sectional overhead door that opens smoothly and can be secured with your own padlock for added security. Inside, you\'ll find an electric power connection (220V socket) - incredibly useful for charging electric vehicles, running power tools, or simply having light while working on your car or accessing stored items. The concrete floor is level and in good condition, suitable for jack stands if you enjoy DIY car maintenance. Many owners use the vertical wall space and ceiling for shelving to store seasonal items, sports equipment, bikes, tools, or anything that doesn\'t fit in a typical apartment. The garage is located in a row of similar boxes with good access via a shared driveway, and the area is well-lit at night. While there are neighbors in adjacent garages, each box is independently owned/rented and lockable. The location on Laan van Meerdervoort in The Hague places you in a residential area with good connections to the city center (10 minutes by car), major roads, and the beach (15 minutes). For residents of nearby apartments without parking, this garage is a game-changer - no more circling for street parking or expensive monthly parking permits. Built in 1988, the structure is solid and functional. This is a straightforward monthly rental - pay your rent and have your secure parking and storage. The rate of €125/month is excellent value compared to city center parking costs (€200+/month) or the hassle of street parking. Available immediately for those tired of parking struggles. Simple one-year rental agreement, can be extended.',
                'type' => 'parking',
                'subtype' => 'garage',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'parking_spots_interior' => 1,
                'parking_spots_exterior' => 0,
                'size' => 18,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 0,
                'has_elevator' => false,
                'year_built' => 1988,
                'energy_class' => null,
                'thermal_insulation_class' => null,
                'heating_type' => null,
                'kitchen_equipped' => false,
                'kitchen_separated' => false,
                'has_cellar' => false,
                'has_laundry' => false,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => null,
                'available_date' => now()->addDays(7),
                'rent_amount' => 125,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '89',
                'street_name' => 'Laan van Meerdervoort',
                'street_line2' => null,
                'city' => 'The Hague',
                'state' => null,
                'postal_code' => '2563 AL',
                'country' => 'NL',
            ],

            // PARKING - INDOOR_SPOT
            [
                'title' => 'Underground Parking Spot in Rotterdam',
                'description' => 'Premium reserved parking space (#B1-47) in a modern secure underground parking garage in the heart of Rotterdam\'s city center on Coolsingel - the ultimate solution for city residents, office workers, or frequent visitors who need reliable, protected parking in the busiest part of the city. This designated parking spot is located on basement level -1 (first underground level), measuring a generous 5.0m x 2.5m (12.5m²), comfortably accommodating any standard sedan, hatchback, SUV, or small van. The spot is clearly marked with your assigned number and painted lines, positioned in a prime location near the elevator and pedestrian exit for maximum convenience - no long walks through dark garages carrying shopping bags or briefcases. The garage facility is state-of-the-art, built in 2015 with top-tier security and amenities: 24/7 access controlled by personal key card (your card, your access, nobody else), comprehensive CCTV surveillance covering all areas with recording, bright LED lighting throughout ensuring safety and visibility at all times, automatic ventilation system maintaining air quality, and elevator access connecting directly to street level and nearby buildings. The garage is professionally managed with regular cleaning and maintenance. Height clearance is 2.2m, suitable for all regular vehicles (not large vans or trucks). One of the standout features is the optional electric vehicle charging - if you drive an EV or are planning to, you can arrange to have a dedicated charging point installed at your spot for an additional monthly fee, making this future-proof parking. The location is absolutely unbeatable: situated on Coolsingel in Rotterdam\'s central business and shopping district, you\'re within 2 minutes walk of major office buildings, luxury shopping at Beurstraverse, restaurants, theaters, and cultural venues. Rotterdam Central Station is 5 minutes walk with direct connections across the Netherlands. For those living in nearby apartments or working in area offices, this parking eliminates the daily stress of finding street parking (nearly impossible in this area) or paying exorbitant hourly rates (€5+/hour). The monthly rate of €175 works out to less than €6 per day - a bargain for city center covered parking with security. The spot is available immediately with flexible rental terms (month-to-month after initial 6-month commitment). Perfect for city apartment residents, business professionals with offices nearby, or even as an investment for renting to others. This is peace of mind parking in Rotterdam\'s premium location - reserve your spot before someone else does.',
                'type' => 'parking',
                'subtype' => 'indoor_spot',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'parking_spots_interior' => 1,
                'parking_spots_exterior' => 0,
                'size' => 12,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => -1,
                'has_elevator' => true,
                'year_built' => 2015,
                'energy_class' => null,
                'thermal_insulation_class' => null,
                'heating_type' => null,
                'kitchen_equipped' => false,
                'kitchen_separated' => false,
                'has_cellar' => false,
                'has_laundry' => false,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => ['security_system'],
                'available_date' => now()->addDays(1),
                'rent_amount' => 175,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '201',
                'street_name' => 'Coolsingel',
                'street_line2' => null,
                'city' => 'Rotterdam',
                'state' => null,
                'postal_code' => '3011 AJ',
                'country' => 'NL',
            ],

            // PARKING - OUTDOOR_SPOT
            [
                'title' => 'Outdoor Parking Space in Arnhem',
                'description' => 'Affordable outdoor parking space (#47) in a secure fenced parking compound located directly adjacent to Arnhem Central Station - an ideal solution for daily commuters, train travelers, or local residents seeking reliable parking without the premium cost of covered garages. This designated parking spot measures 5.0m x 2.3m (approximately 12m²), clearly marked with painted lines and your assigned number, suitable for any regular passenger vehicle including sedans, hatchbacks, station wagons, and SUVs. The surface is well-maintained asphalt that drains properly and remains accessible year-round, even in winter conditions. While this is open-air parking (exposed to weather), the practical benefits and location make it an excellent value proposition. The compound provides essential security features: perimeter fencing around the entire lot preventing unauthorized access, gated entrance with automatic barrier controlled by access card (issued to you), security patrol conducting regular checks throughout the day and night, and good lighting throughout the parking area for safety during dark hours. CCTV cameras monitor the entrance and key areas. The lot is professionally managed with snow clearing in winter and regular maintenance. The location is the real selling point here - you\'re literally next to Arnhem Central Station (2-minute walk to platforms), making this perfect for commuters who drive to the station and take the train to work in Utrecht, Amsterdam, or Nijmegen. No more circling for street parking or risking parking tickets. For city residents in nearby apartments without dedicated parking, this spot provides a permanent solution at a fraction of the cost of city center garage rates. Arnhem\'s Stationsplein area offers shops, cafes, and services, all easily accessible. The monthly rate of just €85 is exceptional value - compare this to covered garage rates (€150-200/month) or daily station parking fees (€10-15/day adds up to €200-300/month). Yes, your car will be exposed to rain, sun, and occasional bird droppings, but for many people the savings and convenience far outweigh having a roof overhead. The spot is available immediately on a flexible month-to-month basis after an initial 3-month period. Perfect for practical-minded commuters, students with cars, or budget-conscious residents who just need a reliable place to park. First come, first served - these affordable spots near the station don\'t stay available long.',
                'type' => 'parking',
                'subtype' => 'outdoor_spot',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'parking_spots_interior' => 0,
                'parking_spots_exterior' => 1,
                'size' => 12,
                'balcony_size' => null,
                'land_size' => null,
                'floor_level' => 0,
                'has_elevator' => false,
                'year_built' => 2010,
                'energy_class' => null,
                'thermal_insulation_class' => null,
                'heating_type' => null,
                'kitchen_equipped' => false,
                'kitchen_separated' => false,
                'has_cellar' => false,
                'has_laundry' => false,
                'has_fireplace' => false,
                'has_air_conditioning' => false,
                'has_garden' => false,
                'has_rooftop' => false,
                'extras' => null,
                'available_date' => now()->addDays(1),
                'rent_amount' => 85,
                'rent_currency' => 'eur',
                'status' => 'vacant',
                'visibility' => 'public',
                'accepting_applications' => true,
                'application_access' => 'open',
                'house_number' => '12',
                'street_name' => 'Stationsplein',
                'street_line2' => null,
                'city' => 'Arnhem',
                'state' => null,
                'postal_code' => '6811 KG',
                'country' => 'NL',
            ],
        ];
    }

    /**
     * Load property images from the seeders/images directory.
     */
    private function loadPropertyImages(Property $property, int $propertyNumber): void
    {
        $imagesPath = database_path("seeders/images/property-{$propertyNumber}");

        if (! File::exists($imagesPath)) {
            return;
        }

        $imageFiles = array_merge(
            File::glob($imagesPath.'/*.jpg'),
            File::glob($imagesPath.'/*.jpeg'),
            File::glob($imagesPath.'/*.png'),
            File::glob($imagesPath.'/*.webp')
        );

        if (empty($imageFiles)) {
            return;
        }

        sort($imageFiles);

        foreach ($imageFiles as $index => $imagePath) {
            $fileName = basename($imagePath);
            $isMain = ($index === 0);

            $disk = StorageHelper::getDisk('private');
            $fileContents = File::get($imagePath);
            $storedPath = "properties/{$property->id}/{$fileName}";

            \Illuminate\Support\Facades\Storage::disk($disk)->put($storedPath, $fileContents);

            PropertyImage::create([
                'property_id' => $property->id,
                'image_path' => $storedPath,
                'sort_order' => $index,
                'is_main' => $isMain,
            ]);
        }
    }
}
