version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.3
      nodejs: 20
    commands:
      - echo "Installing PHP dependencies"
      - composer install --no-dev --optimize-autoloader
      - echo "Installing Node.js dependencies"
      - npm ci
  pre_build:
    commands:
      - echo "Building frontend for production"
      - npm run build
  build:
    commands:
      - echo "Clearing old caches"
      - php artisan config:clear
      - php artisan route:clear
      - php artisan view:clear
      - echo "Caching configuration, routes, and views for production"
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
artifacts:
  files:
    - '**/*'
    - '!node_modules/**'
    - '!tests/**'
  discard-paths: no
