const Ziggy = {
    url: 'http:\/\/rentpath.test:8000',
    port: 8000,
    defaults: {},
    routes: {
        landing: { uri: '\/', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        'privacy.policy': { uri: 'privacy-policy', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        'terms.of.use': { uri: 'terms-of-use', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        'contact.us': { uri: 'contact-us', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        'properties.index': { uri: 'properties', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        'tenant.properties.show': {
            uri: 'properties\/{property}',
            methods: ['GET', 'HEAD'],
            domain: 'rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'tenant.properties.images.show': {
            uri: 'properties\/{property}\/images\/{imageId}',
            methods: ['GET', 'HEAD'],
            domain: 'rentpath.test',
            parameters: ['property', 'imageId'],
            bindings: { property: 'id' },
        },
        'tenant.private.storage': {
            uri: 'private-storage\/{path}',
            methods: ['GET', 'HEAD'],
            wheres: { path: '.*' },
            domain: 'rentpath.test',
            parameters: ['path'],
        },
        'dev.schema': { uri: 'dev\/schema', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        register: { uri: 'register', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        login: { uri: 'login', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        'password.email': { uri: 'forgot-password', methods: ['POST'], domain: 'rentpath.test' },
        'password.reset': { uri: 'reset-password\/{token}', methods: ['GET', 'HEAD'], domain: 'rentpath.test', parameters: ['token'] },
        'password.store': { uri: 'reset-password', methods: ['POST'], domain: 'rentpath.test' },
        'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        'verification.verify': { uri: 'verify-email\/{id}\/{hash}', methods: ['GET', 'HEAD'], domain: 'rentpath.test', parameters: ['id', 'hash'] },
        'verification.send': { uri: 'email\/verification-notification', methods: ['POST'], domain: 'rentpath.test' },
        'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        logout: { uri: 'logout', methods: ['POST'], domain: 'rentpath.test' },
        'manager.properties.index': { uri: 'properties', methods: ['GET', 'HEAD'], domain: 'manager.rentpath.test' },
        profile: { uri: 'profile', methods: ['GET', 'HEAD'], domain: 'manager.rentpath.test' },
        'profile.setup': { uri: 'profile\/setup', methods: ['GET', 'HEAD'], domain: 'manager.rentpath.test' },
        'property-manager.store': { uri: 'profile\/setup', methods: ['POST'], domain: 'manager.rentpath.test' },
        'profile.unverified': { uri: 'profile\/unverified', methods: ['GET', 'HEAD'], domain: 'manager.rentpath.test' },
        'property-manager.edit': { uri: 'edit-profile', methods: ['GET', 'HEAD'], domain: 'manager.rentpath.test' },
        'property-manager.update': { uri: 'edit-profile', methods: ['POST'], domain: 'manager.rentpath.test' },
        'property-manager.document': {
            uri: 'property-manager\/document\/{type}',
            methods: ['GET', 'HEAD'],
            domain: 'manager.rentpath.test',
            parameters: ['type'],
        },
        'properties.create': { uri: 'properties\/create', methods: ['GET', 'HEAD'], domain: 'manager.rentpath.test' },
        'properties.store': { uri: 'properties', methods: ['POST'], domain: 'manager.rentpath.test' },
        'properties.show': {
            uri: 'properties\/{property}',
            methods: ['GET', 'HEAD'],
            domain: 'manager.rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'properties.edit': {
            uri: 'properties\/{property}\/edit',
            methods: ['GET', 'HEAD'],
            domain: 'manager.rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'properties.update': {
            uri: 'properties\/{property}',
            methods: ['PUT'],
            domain: 'manager.rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'properties.destroy': {
            uri: 'properties\/{property}',
            methods: ['DELETE'],
            domain: 'manager.rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'properties.findByToken': {
            uri: 'api\/properties\/token\/{token}',
            methods: ['GET', 'HEAD'],
            domain: 'manager.rentpath.test',
            parameters: ['token'],
        },
        'properties.generateInviteToken': {
            uri: 'properties\/{property}\/invite-token',
            methods: ['POST'],
            domain: 'manager.rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'properties.invalidateInviteToken': {
            uri: 'properties\/{property}\/invite-token',
            methods: ['DELETE'],
            domain: 'manager.rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'properties.togglePublicAccess': {
            uri: 'properties\/{property}\/toggle-public-access',
            methods: ['POST'],
            domain: 'manager.rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'properties.regenerateDefaultToken': {
            uri: 'properties\/{property}\/regenerate-default-token',
            methods: ['POST'],
            domain: 'manager.rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'properties.getInviteTokens': {
            uri: 'properties\/{property}\/invite-tokens',
            methods: ['GET', 'HEAD'],
            domain: 'manager.rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'properties.createCustomToken': {
            uri: 'properties\/{property}\/invite-tokens',
            methods: ['POST'],
            domain: 'manager.rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'properties.updateCustomToken': {
            uri: 'properties\/{property}\/invite-tokens\/{tokenId}',
            methods: ['PUT'],
            domain: 'manager.rentpath.test',
            parameters: ['property', 'tokenId'],
            bindings: { property: 'id' },
        },
        'properties.deleteCustomToken': {
            uri: 'properties\/{property}\/invite-tokens\/{tokenId}',
            methods: ['DELETE'],
            domain: 'manager.rentpath.test',
            parameters: ['property', 'tokenId'],
            bindings: { property: 'id' },
        },
        'images.upload': { uri: 'api\/images\/upload', methods: ['POST'], domain: 'manager.rentpath.test' },
        'images.delete': { uri: 'api\/images\/delete', methods: ['DELETE'], domain: 'manager.rentpath.test' },
        'private.storage': {
            uri: 'private-storage\/{path}',
            methods: ['GET', 'HEAD'],
            wheres: { path: '.*' },
            domain: 'manager.rentpath.test',
            parameters: ['path'],
        },
        'manager.logout': { uri: 'logout', methods: ['POST'], domain: 'manager.rentpath.test' },
        dashboard: { uri: 'dashboard', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        'tenant.profile.edit': { uri: 'profile\/tenant\/edit', methods: ['GET', 'HEAD'], domain: 'rentpath.test' },
        'tenant.profile.update': { uri: 'profile\/tenant\/edit', methods: ['POST'], domain: 'rentpath.test' },
        'tenant.profile.document': {
            uri: 'tenant-profile\/document\/{type}',
            methods: ['GET', 'HEAD'],
            domain: 'rentpath.test',
            parameters: ['type'],
        },
        'applications.create': {
            uri: 'properties\/{property}\/apply',
            methods: ['GET', 'HEAD'],
            domain: 'rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'applications.store': {
            uri: 'properties\/{property}\/apply',
            methods: ['POST'],
            domain: 'rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'applications.save-draft': {
            uri: 'properties\/{property}\/apply\/draft',
            methods: ['POST'],
            domain: 'rentpath.test',
            parameters: ['property'],
            bindings: { property: 'id' },
        },
        'applications.show': {
            uri: 'applications\/{application}',
            methods: ['GET', 'HEAD'],
            domain: 'rentpath.test',
            parameters: ['application'],
            bindings: { application: 'id' },
        },
        'applications.update': {
            uri: 'applications\/{application}',
            methods: ['PUT'],
            domain: 'rentpath.test',
            parameters: ['application'],
            bindings: { application: 'id' },
        },
        'applications.destroy': {
            uri: 'applications\/{application}',
            methods: ['DELETE'],
            domain: 'rentpath.test',
            parameters: ['application'],
            bindings: { application: 'id' },
        },
        'applications.withdraw': {
            uri: 'applications\/{application}\/withdraw',
            methods: ['POST'],
            domain: 'rentpath.test',
            parameters: ['application'],
            bindings: { application: 'id' },
        },
        'storage.private': { uri: 'storage\/{path}', methods: ['GET', 'HEAD'], wheres: { path: '.*' }, parameters: ['path'] },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
